In [30]:
[[123,12,123,12,33], [],[]] #list

[[123, 12, 123, 12, 33], [], []]

In [32]:
import numpy #numpy arrays mainly used for multidimensional arrays
n = numpy.arange(27) #random list of values from 0-27
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [33]:
type(n)

numpy.ndarray

In [34]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [36]:
n.reshape(3,9) #reshaping the 1:27 to a 3:9 (2d array)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [37]:
n.reshape(3,3,3) #3d array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [39]:
m = numpy.asarray([[123,12,123,12,33], [],[]]) #numpy array
m
type(m)

numpy.ndarray

In [ ]:
#pandas arrays are based on numpy arrays
#numpy requrements for many things

In [40]:
import cv2