In [54]:
[[123,12,123,12,33], [],[]] #list

[[123, 12, 123, 12, 33], [], []]

In [55]:
import numpy #numpy arrays mainly used for multidimensional arrays
n = numpy.arange(27) #random list of values from 0-27
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [56]:
type(n)

numpy.ndarray

In [57]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [58]:
n.reshape(3,9) #reshaping the 1:27 to a 3:9 (2d array)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [59]:
n.reshape(3,3,3) #3d array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [60]:
m = numpy.asarray([[123,12,123,12,33], [],[]]) #numpy array (converting array to a numpy array)
m
type(m)

numpy.ndarray

In [61]:
#pandas arrays are based on numpy arrays
#numpy requrements for many things

In [62]:
import cv2

In [65]:
#images to numpy arrays
im_g = cv2.imread("/Users/andrewyip/Desktop/numpy/smallgray.png", 0) #0 read in grayscale, #1 means bgr(blue,gree,red)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [67]:
#numpy arrays to images
cv2.imwrite("/Users/andrewyip/Desktop/numpy/newsmallgray.png", im_g)


True

In [69]:
#indexing/slicing/iterating numpy arrays
a = [1,2,3]
a[0:2]


[1, 2]

In [70]:
#indexing through a numpy array
im_g2 = im_g
im_g2

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [71]:
im_g2[0:2, 2:4] #gives us first two rows, then columns from 2-4

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [72]:
im_g2.shape #sees the dimensions

(3, 5)

In [73]:
im_g2[0,4]

143

In [74]:
#iterating through a numpy array

#iterate through rows
for i in im_g2: #like 2d array in java (nested for loop)
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [75]:
#iterate through columns
for i in im_g2.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [76]:
#to iterate and get individual values:
for i in im_g2.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [ ]:
#stacking and splitting numpy arrays


In [80]:
#stacking numpy arrays

#horizontal stack
ims = numpy.hstack((im_g, im_g)) #horizontal stack (have a tuple of numpy arrays) (horizontal means side by side)
ims #stacks row by row onto each other into one row by longer

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [81]:
#vertical stack

ims = numpy.vstack((im_g, im_g)) #vertical stack (have a tuple of numpy arrays)
ims #stacks columns on columns (concatinate arrays vertically)

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [86]:
#splitting an array into smaller arrays

#lst = numpy.hsplit(ims, 5) #horizontal split (means side by side)
#lst
ims #we will be splitting ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [87]:
lst = numpy.hsplit(ims, 5) #horizontal split (columns)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [88]:
#splits the array sideways 

lst = numpy.vsplit(ims,3) 
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182],
        [187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]